site_name: Cindy的笔记本
site_url: https://cindyzhou2003.github.io/mymkdocs/
repo_name: Cindy's notebook
repo_url: https://github.com/CindyZhou2003/mymkdocs  #存储库URL
# edit_uri: tree/master/docs  #每个文档的顶部显示一个编辑按钮，""则隐藏
site_description: Cindy的笔记本
copyright: Copyright &copy; 2024 <a href="https://github.com/CindyZhou2003/mymkdocs"  target="_blank" rel="noopener">Cindy</a>

theme: 
  name: material
  language: zh
  favicon: assets/images/favicon.png
  custom_dir: docs/overrides
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font:
    text: LXGW WenKai Screen
    code: JetBrains Mono
  palette:     #切换昼夜模式的颜色，审美差就用默认，专业点就自定义
    - media: "(prefers-color-scheme: light)" 
      scheme: default  #配色方案：浅色模式
      primary: cyan  #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
      accent: cyan  #强调色，默认蓝，可以交互的元素如悬停链接、按钮和滚动条
      toggle:
        icon: material/weather-sunny #图标，太阳
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"  
      scheme: slate  #配色方案：深色模式
      # primary: Brown  #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
      toggle:
        icon: material/weather-night  #图标，月亮
        name: Switch to light mode


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols  #智能符号
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true


extra_css:
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - css/extra.css
  - css/neoteroi-mkdocs.css
  - css/style.css
  

extra_javascript:
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  - js/katex.js
  - js/tablesort.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CindyZhou2003/mymkdocs

plugins:
  - search

nav:
  - Home:
    - index.md
  - Courses:
    - 高级数据结构与算法分析: Courses/ADS.md
    - 数据库系统: Courses/DB.md
    - 离散数学及其应用: Courses/DM.md
    - 数据结构基础: Courses/FDS.md
    - 机器学习（国际化）: Courses/ML.md
    - 面向对象程序设计: Courses/OOP.md
    - 信息安全原理: Courses/PIS.md
  - Skills:
    - 算法: skills/Algorithm.md
    - 深度学习: skills/deeplearning.md
  - Other:
    - IELTS: other/IELTS.md
    - Test: other/test.md
   

use_directory_urls: false #解决图片相对路径无法解析的问题