name: ci

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Step 3: Install dependencies
      - run: pip install mkdocs-material mkdocs-blogging-plugin

      # Step 4: Build the site
      - run: mkdocs build

      # Step 5: Add a .nojekyll file to prevent Jekyll processing
      - run: echo "" > ./site/.nojekyll

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --clean
