name: Deploy MkDocs Site

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install MkDocs and plugins
      - run: |
          pip install mkdocs-material
          pip install mkdocs-blogging-plugin
          pip install mkdocs-git-revision-date-localized-plugin

      # Step 4: Build the site
      - run: mkdocs build

      # Step 5: Add a .nojekyll file to prevent GitHub Pages from using Jekyll
      - run: touch site/.nojekyll

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --clean

