name: Deploy MkDocs Site

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install MkDocs and plugins
        run: |
          pip install mkdocs-material
          pip install mkdocs-blogging-plugin
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-statistics-plugin


      # Step 4: Build the MkDocs site
      - name: Build MkDocs site
        run: mkdocs build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --clean --verbose


